version: '3.7'

services:

  python:
    build: .
    container_name: python-nft-api
    restart: unless-stopped
    networks:
      python-api:
        ipv4_address: 172.210.0.120

networks:

  python-api:
    name: python-api
    ipam:
      config:
        - subnet: 172.210.0.0/24